### ISSUE TITLE
plot_event_pipeline not displaying inline plots in Jupyter notebook

### ISSUE THREAD

**Issue by OliverEvans96** [UCBerkeleySETI/turbo_seti#188]
**Describe the bug**

`plot_event_pipeline` runs successfully and generates `.png` outputs, but does not show the plots inline in the notebook.

**Relevant BL files (.fil, .h5)**

http://blpd14.ssl.berkeley.edu/voyager_2020/single_coarse_channel/single_coarse_guppi_59046_80036_DIAG_VOYAGER-1_0011.rawspec.0000.h5

**To Reproduce**

_TL;DR_ run `plot_event_pipeline` in a Jupyter notebook

1. Binder is a Jupyter service that allows anyone to run a notebook from a web browser in the exact environment it was created. Run my demo of this bug from your browser by clicking the following button (or [this link](https://mybinder.org/v2/gh/OliverEvans96/turbo-seti-waterfall-plot-bug-demo/main?filepath=demo.ipynb)):
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/OliverEvans96/turbo-seti-waterfall-plot-bug-demo/main?filepath=demo.ipynb)
2. Run all cells

OR

1. Download my bug demo locally from https://github.com/OliverEvans96/turbo-seti-waterfall-plot-bug-demo

```bash
# Clone the repo
git clone https://github.com/OliverEvans96/turbo-seti-waterfall-plot-bug-demo.git
```

2. Create, and activate the conda env

```bash
# Create the environment from the definition file
conda env create -f environment.yml

# Activate the new environment
conda activate turbo_seti_waterfall_bug

# Create a Jupyter kernel for this environment to make it accessible from a notebook
python -m ipykernel install --user --name=turbo_seti_waterfall_bug
```

3. Start a Jupyter server and open `demo.ipynb`
4. Select the `turbo_seti_waterfall_bug` kernel (Kernel > Change Kernel)
5. Run all cells

**Expected behavior**

Inline plots displayed

![2021-02-20-113232_1255x530_scrot](https://user-images.githubusercontent.com/15915043/108602351-749de100-736f-11eb-9327-c14712c1a59e.png)

**Screenshots**

This is what actually happens (no output is produced):

![2021-02-20-113249_1281x337_scrot](https://user-images.githubusercontent.com/15915043/108602352-75367780-736f-11eb-9199-54f7d0a4215e.png)

**Setup**

_environment.yml_
```yaml
name: turbo_seti_waterfall_bug
channels:
  - defaults
dependencies:
  # Core requirements
  - python=3.7
  - pip
  - tqdm
  # Allow a Jupyter kernel to be created for this env
  - ipykernel
  # Install some git dependencies using pip
  - pip:
    - git+https://github.com/UCBerkeleySETI/blimpy
    - git+https://github.com/OliverEvans96/turbo_seti@show-waterfall
```

**Additional context**

Seems to be caused by https://github.com/UCBerkeleySETI/turbo_seti/commit/67650ada58eb1fdd77491ccfeac419ab4cd845f4, addressed by #187.
